-- MySQL Script generated by MySQL Workbench
-- Tue Jan 14 12:50:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trabai_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trabai_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabai_BD` DEFAULT CHARACTER SET utf8 ;
USE `Trabai_BD` ;

-- -----------------------------------------------------
-- Table `Trabai_BD`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`NUMERO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`NUMERO_CLIENTE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE_ID` INT NOT NULL,
  `Numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Id`, `CLIENTE_ID`),
  INDEX `fk_NUMERO_CLIENTE_CLIENTE_idx` (`CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NUMERO_CLIENTE_CLIENTE`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`EMAIL_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`EMAIL_CLIENTE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email_Cliente` VARCHAR(100) NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`Id`, `CLIENTE_ID`),
  INDEX `fk_EMAIL_CLIENTE_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EMAIL_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ENDERECO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ENDERECO_CLIENTE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Endereco` VARCHAR(100) NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`Id`, `CLIENTE_ID`),
  INDEX `fk_Endereco_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`FUNCIONARIO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Salario` DECIMAL(10,2) NOT NULL,
  `Data_Contratacao` DATE NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ATENDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ATENDENTE` (
  `FUNCIONARIO_Id` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_Id`),
  CONSTRAINT `fk_ATENDENTE_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`FUNCIONARIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`CLIENTE_ATENDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`CLIENTE_ATENDENTE` (
  `ATENDENTE_FUNCIONARIO_Id` INT NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ATENDENTE_FUNCIONARIO_Id`, `CLIENTE_ID`),
  INDEX `fk_CLIENTE_ATENDENTE_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_ATENDENTE_ATENDENTE1`
    FOREIGN KEY (`ATENDENTE_FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`ATENDENTE` (`FUNCIONARIO_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_ATENDENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`LOJA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` INT(14) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`, `CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`FUNCIONARIO_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`FUNCIONARIO_LOJA` (
  `LOJA_Id` INT NOT NULL,
  `FUNCIONARIO_Id` INT NOT NULL,
  PRIMARY KEY (`LOJA_Id`, `FUNCIONARIO_Id`),
  INDEX `fk_FUNCIONARIO_LOJA_FUNCIONARIO1_idx` (`FUNCIONARIO_Id` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIO_LOJA_LOJA1`
    FOREIGN KEY (`LOJA_Id`)
    REFERENCES `Trabai_BD`.`LOJA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_LOJA_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`FUNCIONARIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`GERENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`GERENTE` (
  `LOJA_Id` INT NOT NULL,
  `FUNCIONARIO_Id` INT NOT NULL,
  PRIMARY KEY (`LOJA_Id`, `FUNCIONARIO_Id`),
  INDEX `fk_GERENTE_LOJA1_idx` (`LOJA_Id` ASC) VISIBLE,
  INDEX `fk_GERENTE_FUNCIONARIO1_idx` (`FUNCIONARIO_Id` ASC) VISIBLE,
  CONSTRAINT `fk_GERENTE_LOJA1`
    FOREIGN KEY (`LOJA_Id`)
    REFERENCES `Trabai_BD`.`LOJA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GERENTE_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`FUNCIONARIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`COMPRA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Valor_Total` DECIMAL(10,2) NULL,
  `CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`Id`, `CLIENTE_ID`),
  INDEX `fk_COMPRA_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`COMPRA_CAIXA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`COMPRA_CAIXA` (
  `COMPRA_Id` INT NOT NULL,
  `COMPRA_CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`COMPRA_Id`, `COMPRA_CLIENTE_ID`),
  CONSTRAINT `fk_COMPRA_CAIXA_COMPRA1`
    FOREIGN KEY (`COMPRA_Id` , `COMPRA_CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`COMPRA` (`Id` , `CLIENTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`CAIXA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`CAIXA` (
  `FUNCIONARIO_Id` INT NOT NULL,
  `COMPRA_CAIXA_COMPRA_Id` INT NOT NULL,
  `COMPRA_CAIXA_COMPRA_CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_Id`, `COMPRA_CAIXA_COMPRA_Id`, `COMPRA_CAIXA_COMPRA_CLIENTE_ID`),
  INDEX `fk_CAIXA_COMPRA_CAIXA1_idx` (`COMPRA_CAIXA_COMPRA_Id` ASC, `COMPRA_CAIXA_COMPRA_CLIENTE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CAIXA_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`FUNCIONARIO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAIXA_COMPRA_CAIXA1`
    FOREIGN KEY (`COMPRA_CAIXA_COMPRA_Id` , `COMPRA_CAIXA_COMPRA_CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`COMPRA_CAIXA` (`COMPRA_Id` , `COMPRA_CLIENTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`VENDAS` (
  `idVENDAS` INT NOT NULL AUTO_INCREMENT,
  `LOJA_Id` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Valor_Total` DECIMAL(10,2) NULL,
  `Num_Vendas` INT NULL,
  PRIMARY KEY (`idVENDAS`, `LOJA_Id`),
  INDEX `fk_VENDAS_LOJA1_idx` (`LOJA_Id` ASC) VISIBLE,
  CONSTRAINT `fk_VENDAS_LOJA1`
    FOREIGN KEY (`LOJA_Id`)
    REFERENCES `Trabai_BD`.`LOJA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ENDERECO_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ENDERECO_LOJA` (
  `LOJA_CNPJ` INT(14) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LOJA_CNPJ`, `Endereco`),
  CONSTRAINT `fk_ENDERECO_LOJA_LOJA1`
    FOREIGN KEY (`LOJA_CNPJ`)
    REFERENCES `Trabai_BD`.`LOJA` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`TIPO_PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`TIPO_PAGAMENTO` (
  `Tipo_Pagamento` INT NOT NULL,
  PRIMARY KEY (`Tipo_Pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`PAGAMENTO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CAIXA_FUNCIONARIO_Id` INT NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  `TIPO_PAGAMENTO_Tipo_Pagamento` INT NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`Id`, `CAIXA_FUNCIONARIO_Id`, `CLIENTE_ID`, `TIPO_PAGAMENTO_Tipo_Pagamento`),
  INDEX `fk_PAGAMENTO_CAIXA1_idx` (`CAIXA_FUNCIONARIO_Id` ASC) VISIBLE,
  INDEX `fk_PAGAMENTO_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  INDEX `fk_PAGAMENTO_TIPO_PAGAMENTO1_idx` (`TIPO_PAGAMENTO_Tipo_Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_PAGAMENTO_CAIXA1`
    FOREIGN KEY (`CAIXA_FUNCIONARIO_Id`)
    REFERENCES `Trabai_BD`.`CAIXA` (`FUNCIONARIO_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGAMENTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `Trabai_BD`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGAMENTO_TIPO_PAGAMENTO1`
    FOREIGN KEY (`TIPO_PAGAMENTO_Tipo_Pagamento`)
    REFERENCES `Trabai_BD`.`TIPO_PAGAMENTO` (`Tipo_Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`FORNECEDOR` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` INT(14) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`PEDIDO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `LOJA_Id` INT NOT NULL,
  `LOJA_CNPJ` INT(14) NOT NULL,
  `Data_Pedido` DATE NOT NULL,
  `Data_Entrega` DATE NOT NULL,
  `FORNECEDOR_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `LOJA_Id`, `LOJA_CNPJ`, `FORNECEDOR_Id`),
  INDEX `fk_PEDIDO_LOJA1_idx` (`LOJA_Id` ASC, `LOJA_CNPJ` ASC) VISIBLE,
  INDEX `fk_PEDIDO_FORNECEDOR1_idx` (`FORNECEDOR_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_LOJA1`
    FOREIGN KEY (`LOJA_Id` , `LOJA_CNPJ`)
    REFERENCES `Trabai_BD`.`LOJA` (`Id` , `CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_Id`)
    REFERENCES `Trabai_BD`.`FORNECEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ITEM_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ITEM_PEDIDO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PEDIDO_Id` INT NOT NULL,
  `PEDIDO_LOJA_Id` INT NOT NULL,
  `PEDIDO_LOJA_CNPJ` INT(14) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Quantidade` VARCHAR(255) NULL,
  `Preco_Unitario` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Id`, `PEDIDO_Id`, `PEDIDO_LOJA_Id`, `PEDIDO_LOJA_CNPJ`),
  INDEX `fk_ITEM_PEDIDO_PEDIDO1_idx` (`PEDIDO_Id` ASC, `PEDIDO_LOJA_Id` ASC, `PEDIDO_LOJA_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_Id` , `PEDIDO_LOJA_Id` , `PEDIDO_LOJA_CNPJ`)
    REFERENCES `Trabai_BD`.`PEDIDO` (`Id` , `LOJA_Id` , `LOJA_CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ENDERECO_FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ENDERECO_FORNECEDOR` (
  `FORNECEDOR_Id` INT NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FORNECEDOR_Id`),
  CONSTRAINT `fk_ENDERECO_FORNECEDOR_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_Id`)
    REFERENCES `Trabai_BD`.`FORNECEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ESTOQUE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`CATEGORIA` (
  `Categoria` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`FABRICANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`FABRICANTE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`PRODUTO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CATEGORIA_Categoria` INT NOT NULL,
  `Descricao` VARCHAR(255) NULL,
  `Preco_Base` DECIMAL(10,2) NULL,
  `Peso` DECIMAL(10,2) NULL,
  `FABRICANTE_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `CATEGORIA_Categoria`, `FABRICANTE_Id`),
  INDEX `fk_PRODUTO_CATEGORIA1_idx` (`CATEGORIA_Categoria` ASC) VISIBLE,
  INDEX `fk_PRODUTO_FABRICANTE1_idx` (`FABRICANTE_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_Categoria`)
    REFERENCES `Trabai_BD`.`CATEGORIA` (`Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_FABRICANTE1`
    FOREIGN KEY (`FABRICANTE_Id`)
    REFERENCES `Trabai_BD`.`FABRICANTE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ESTOQUE_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ESTOQUE_PRODUTO` (
  `ESTOQUE_Id` INT NOT NULL,
  `Quantidade_Disponivel` INT(10) NOT NULL,
  `PRODUTO_Id` INT NOT NULL,
  PRIMARY KEY (`ESTOQUE_Id`, `PRODUTO_Id`),
  INDEX `fk_ESTOQUE_PRODUTO_PRODUTO1_idx` (`PRODUTO_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ESTOQUE_PRODUTO_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_Id`)
    REFERENCES `Trabai_BD`.`ESTOQUE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTOQUE_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_Id`)
    REFERENCES `Trabai_BD`.`PRODUTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`PRODUTO_FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`PRODUTO_FORNECEDOR` (
  `PRODUTO_Id` INT NOT NULL,
  `FORNECEDOR_Id` INT NOT NULL,
  PRIMARY KEY (`PRODUTO_Id`, `FORNECEDOR_Id`),
  INDEX `fk_PRODUTO_FORNECEDOR_FORNECEDOR1_idx` (`FORNECEDOR_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR_PRODUTO1`
    FOREIGN KEY (`PRODUTO_Id`)
    REFERENCES `Trabai_BD`.`PRODUTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_Id`)
    REFERENCES `Trabai_BD`.`FORNECEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`METRAGEM_UNIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`METRAGEM_UNIDADE` (
  `Tipo` INT NOT NULL,
  PRIMARY KEY (`Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ITEM_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ITEM_COMPRA` (
  `COMPRA_Id` INT NOT NULL,
  `PRODUTO_Id` INT NOT NULL,
  `Quantidade` DECIMAL(10,2) NULL,
  `Peso` DECIMAL(10,2) NULL,
  `METRAGEM_UNIDADE_Tipo` INT NOT NULL,
  PRIMARY KEY (`COMPRA_Id`, `PRODUTO_Id`, `METRAGEM_UNIDADE_Tipo`),
  INDEX `fk_ITEM_COMPRA_PRODUTO1_idx` (`PRODUTO_Id` ASC) VISIBLE,
  INDEX `fk_ITEM_COMPRA_METRAGEM_UNIDADE1_idx` (`METRAGEM_UNIDADE_Tipo` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_COMPRA_COMPRA1`
    FOREIGN KEY (`COMPRA_Id`)
    REFERENCES `Trabai_BD`.`COMPRA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_COMPRA_PRODUTO1`
    FOREIGN KEY (`PRODUTO_Id`)
    REFERENCES `Trabai_BD`.`PRODUTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_COMPRA_METRAGEM_UNIDADE1`
    FOREIGN KEY (`METRAGEM_UNIDADE_Tipo`)
    REFERENCES `Trabai_BD`.`METRAGEM_UNIDADE` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`ESTOQUE_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`ESTOQUE_LOJA` (
  `ESTOQUE_Id` INT NOT NULL,
  `LOJA_Id` INT NOT NULL,
  `LOJA_CNPJ` INT(14) NOT NULL,
  PRIMARY KEY (`ESTOQUE_Id`, `LOJA_Id`, `LOJA_CNPJ`),
  INDEX `fk_ESTOQUE_LOJA_LOJA1_idx` (`LOJA_Id` ASC, `LOJA_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_ESTOQUE_LOJA_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_Id`)
    REFERENCES `Trabai_BD`.`ESTOQUE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTOQUE_LOJA_LOJA1`
    FOREIGN KEY (`LOJA_Id` , `LOJA_CNPJ`)
    REFERENCES `Trabai_BD`.`LOJA` (`Id` , `CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`EMAIL_FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`EMAIL_FORNECEDOR` (
  `FORNECEDOR_Id` INT NOT NULL,
  `Email` VARCHAR(100) NULL,
  PRIMARY KEY (`FORNECEDOR_Id`),
  CONSTRAINT `fk_EMAIL_FORNECEDOR_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_Id`)
    REFERENCES `Trabai_BD`.`FORNECEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Trabai_BD`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabai_BD`.`TELEFONE` (
  `FORNECEDOR_Id` INT NOT NULL,
  `Numero` INT(14) NOT NULL,
  PRIMARY KEY (`FORNECEDOR_Id`),
  CONSTRAINT `fk_TELEFONE_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_Id`)
    REFERENCES `Trabai_BD`.`FORNECEDOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
